# Generated by Django 4.0.4 on 2022-04-22 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='date',
            field=models.DateField(default='1234-09-01'),
            preserve_default=False,
        ),
    ]
